#!/usr/bin/env bash

# uh, which?
exists() {
  command -v "${1}" &>/dev/null # &>/dev/null: redirects both stdout and stderr to /dev/null also an alternate of /dev/null 2>&1
}

# not zelda
link() {
  if [ -e "$2" ]; then
    if [ "$(readlink "$2")" = "$1" ]; then
      notice "Skipped $1"
      return 0
    elif [[ "${3:-"true"}" == "true" ]]; then
      mv "$2" "$2.backup"
      notice "Moved $2 to $2.backup"
    fi
  fi

  ln -sf "$1" "$2"
  success "Linked $1 to $2"
}

# silent cloner
clone() {
  git clone --depth "${3:-5}" --quiet "$1" "$2" &>/dev/null
}

# silent updater
rebase() {
  git pull --rebase origin master &>/dev/null
}

# download
downf() {
  curl -L "${1}" -o "${2}" &>/dev/null
}

# append from one file to another
fappend() {
  if [ -f "${1}" ]; then
    cat "$1" >> "$2" &>/dev/null
  fi
}

# silent rm
silrem() {
  if [ -f "${1}" ]; then
    rm -f "${1}" &>/dev/null
  fi
}

# create
touchf() {
  if [ ! -f "${1}" ]; then
    touch "${1}" &>/dev/null
  fi
}